version: '3.8'

# Simple deployment without SSL/Nginx - HTTP only
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-checkin-app-simple
    restart: unless-stopped
    ports:
      - "80:3000"  # Direct access on port 80
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching
  redis:
    image: redis:alpine
    container_name: qr-checkin-redis-simple
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: